export { default as Navbar } from "./Navbar";
export { default as Main } from "./Main";
export { default as Tours } from "./Tours";
export { default as PictureSlider } from "./PictureSlider";
export { default as Distination } from "./DestinationSlider";
export { default as Tickets } from "./Tickets";
export { default as Facts } from "./Facts";
export { default as Landscapes } from "./Landscapes";
export { default as Order } from "./Order";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer"